### ISSUE TITLE
alias auto doesn't work withe terminator

### ISSUE THREAD

**Issue by martinsam** [jeroenbourgois/terminator#1]
I also use aliases, zsh and terminator, all it's ok .

However when I try to launch "custom command" for a panel at the start of terminator : 
"zsh:1: command not found:" 

Do you have some idea ?

**Comment by jeroenbourgois** [comment]
Sry, just saw this right nog!

Are you still having this issue?

**Comment by mehditlili** [comment]
I think terminator doesn't source .bashrc when running custom commands. Not even .profile . Is there any way of tricking that?

**Comment by farcis** [comment]
I am facing the same problem. Is there any idea?

**Comment by jeroenbourgois** [comment]
Sorry @farcis I have been using Fish shell for months. I will try and look into this this week

**Comment by jeroenbourgois** [comment]
@farcis with custom commands, you mean the ones of oh-my-zsh? Anyway, sorry to dissapoint but I will clean this repo up since I use Fish now. I will put the current version in a tag `zsh` and update to Fish config. I recommend you give it a try!

**Comment by farcis** [comment]
Thanks! i will give a try to fish

2016-04-26 12:16 GMT-03:00 Jeroen Bourgois notifications@github.com:
